### PR TITLE
Updates required by pyswisseph 2.08.00-0

### LINKED ISSUE #40: fixstar function update
olo,
thx for sharing this lib, useful, though limited (to west. trad. astro.).

quote from swisseph (ch) docs:
"For new projects, we recommend using the new functions swe_fixstar2_ut() and swe_fixstar2(). Performance will be a lot better  if a great number of fixed star calculations are done. "
with swisseph 2.07, new fixstar functions were added.
another quote :
"The  fixed  stars  functions  only  work  if  the  fixed  stars  data  file  sefstars.txt  is  found  in  the  ephemeris  path.  If the file sefstars.txt  is  not  found,  the  old  file  fixstars.cat  is  searched  and  used  instead,  if  present.  However,  it  is  strongly recommended to *not* use the old file anymore. The data in the file are outdated, and the algorithms are also not as accurate as those used with the file sefstars.txt. "

regarding this, comparing flatlib/const.py and sefstars.txt (recommended above), to use sefstars.txt, constants in const.py should be updated (i believe, if they are used to search fixstars.cat file):
# chi: from sefstars.txt: Zuben Eschamali
STAR_ZUBEN_ESCHAMALI = 'Zuben Eschamali'
# chi: from sefstars.txt: Rigel Kentaurus
STAR_RIGEL_KENTAURUS = 'Rigel Kentaurus'

so, sefstars.txt could be added to flatlib/resources/swefiles folder.

not sure if implementing (or completely substituting old) new swe_fixstar2() and swe_fixstar2_ut() makes any sense for this library.

pyswisseph has been updated to 2.08, recently. 

s love nia

### PR DESCRIPTION
**Pull request by astrorigin**
Fixes #40, #41

### CODE REVIEW

**Comment by xAlstrat** [comment]
I tried this solution and I got this error:

```
python3.6/site-packages/flatlib/ephem/swe.py", line 71, in sweObject
    sweList, flg = swisseph.calc_ut(jd, sweObj)
```
swisseph.Error: SwissEph file 'seas_18.se1' not found in PATH '.:/users/ephe2/:/users/ephe/'

I had to force the version to the previous one.

I'm working with ubuntu 18 and python 3.6 with virtualenv.

**Comment by astrorigin** [comment]
> I tried this solution and I got this error:
> 
> ```
> python3.6/site-packages/flatlib/ephem/swe.py", line 71, in sweObject
>     sweList, flg = swisseph.calc_ut(jd, sweObj)
> ```
> 
> swisseph.Error: SwissEph file 'seas_18.se1' not found in PATH '.:/users/ephe2/:/users/ephe/'
> 
> I had to force the version to the previous one.
> 
> I'm working with ubuntu 18 and python 3.6 with virtualenv.

This is unrelated. A previous call to swe.set_ephe_path(...) is missing or faulty. Or you have not installed ephemeris (*.se1) files.

**Comment by zgpnuaa** [comment]
After applying the fixes above, the following error occurred when I calculated chart：

>  File "D:\WebDjango\mysite\mysite\astrologychart\views.py", line 54, in calculate_astrology
    chart = Chart(date, pos, IDs=[const.SUN, const.MOON, const.MERCURY, const.VENUS, const.MARS, const.JUPITER, const.SATURN, const.URANUS, const.NEPTUNE, const.PLUTO, const.CHI
RON, const.NORTH_NODE, const.SOUTH_NODE ])
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib\chart.py", line 53, in __init__
    self.objects = ephem.getObjectList(IDs, date, pos)
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib\ephem\ephem.py", line 34, in getObjectList
    objList = [getObject(ID, date, pos) for ID in IDs]
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib\ephem\ephem.py", line 34, in <listcomp>
    objList = [getObject(ID, date, pos) for ID in IDs]
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib\ephem\ephem.py", line 29, in getObject
    obj = eph.getObject(ID, date.jd, pos.lat, pos.lon)
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib\ephem\eph.py", line 48, in getObject
    obj = swe.sweObject(ID, jd)
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib\ephem\swe.py", line 71, in sweObject
    def sweObjectLon(obj, jd):
IndexError: tuple index out of range
@astrorigin @joaoventura @xAlstrat

**Comment by craviee** [comment]
@zgpnuaa It seems that you didn't apply the fix on `sweObjectLon`
```
def sweObjectLon(obj, jd):
    """ Returns the longitude of an object. """
    sweObj = SWE_OBJECTS[obj]
    sweList, flg = swisseph.calc_ut(jd, sweObj)
    return sweList[0]
```

**Comment by zgpnuaa** [comment]
chart = Chart(date, pos, IDs=[const.SUN, const.MOON, const.MERCURY, const.VENUS, const.MARS, const.JUPITER, const.SATURN, const.URANUS, const.NEPTUNE, const.PLUTO, const.CHI
RON, const.NORTH_NODE, const.SOUTH_NODE ])
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib-0.2.2.dev0-py3.7.egg\flatlib\chart.py", line 53, in __init__
    self.objects = ephem.getObjectList(IDs, date, pos)
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib-0.2.2.dev0-py3.7.egg\flatlib\ephem\ephem.py", line 35, in getObjectList
    objList = [getObject(ID, date, pos) for ID in IDs]
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib-0.2.2.dev0-py3.7.egg\flatlib\ephem\ephem.py", line 35, in <listcomp>
    objList = [getObject(ID, date, pos) for ID in IDs]
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib-0.2.2.dev0-py3.7.egg\flatlib\ephem\ephem.py", line 30, in getObject
    obj = eph.getObject(ID, date.jd, pos.lat, pos.lon)
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib-0.2.2.dev0-py3.7.egg\flatlib\ephem\eph.py", line 48, in getObject
    obj = swe.sweObject(ID, jd)
  File "D:\DjangoWebSite\DjangoWebSite\mysite\envmysite\lib\site-packages\flatlib-0.2.2.dev0-py3.7.egg\flatlib\ephem\swe.py", line 66, in sweObject
    sweList, flg = swisseph.calc_ut(jd, sweObj)
**swisseph.Error: SwissEph file 'seas_18.se1' not found in PATH '\sweph\ephe\'**

After applying  all the fixes above, the above same  error as @xAlstrat  occurred when I calculated chart. @craviee   @astrorigin @joaoventura

**Comment by zgpnuaa** [comment]
Cool!
I just solved this problem. 
In flatlib, the path of (*.se1) files is 'flatlib/resources/sweiles', which may be due to the default path of pyswisseph 2.8.0 being '\sweph\ephe'.
image

So I set up a folder in the root directory of my project with path '\sweph\ephe', and copy the (*.se1) files in the path 'flatlib/resources/sweiles' to this folder, and in function of sweObject(obj, jd) i set swisseph.set_ephe_path(path), and then I can run it.
`def sweObject(obj, jd):
    """ Returns an object from the Ephemeris. """
    path = 'sweph/ephe/'
    swisseph.set_ephe_path(path)
    sweObj = SWE_OBJECTS[obj]
    sweList, flg = swisseph.calc_ut(jd, sweObj)
    return {
        'id': obj,
        'lon': sweList[0],
        'lat': sweList[1],
        'lonspeed': sweList[3],
        'latspeed': sweList[4]
    }`

image


image

Flatlib and Pyswisseph are great works.
 Hope the two authors can negotiate the path of the(*.se1) files , and then update the requirement to pyswisseph 2.8.0.
Thanks.
 @joaoventura @astrorigin @craviee @xAlstrat

**Comment by andandio** [comment]
Thank you, @zgpnuaa !
You can also reset the path without copying the files to a new location.
Inside `def sweObject(obj, jd): `
reset the path that gets set in `__inity__.py` with:
```
path = flatlib.PATH_RES + 'swefiles'
swisseph.set_ephe_path(path)
```

**Comment by zgpnuaa** [comment]
> Thank you, @zgpnuaa !
> You can also reset the path without copying the files to a new location.
> Inside `def sweObject(obj, jd): `
> reset the path that gets set in `__inity__.py` with:
> 
> ```
> path = flatlib.PATH_RES + 'swefiles'
> swisseph.set_ephe_path(path)
> ```

Thank you. @andandio   It works!
`def sweObject(obj, jd):
    """ Returns an object from the Ephemeris. """

    path = flatlib.PATH_RES + 'swefiles'
    swisseph.set_ephe_path(path)

    sweObj = SWE_OBJECTS[obj]
    sweList, flg = swisseph.calc_ut(jd, sweObj)
    return {
        'id': obj,
        'lon': sweList[0],
        'lat': sweList[1],
        'lonspeed': sweList[3],
        'latspeed': sweList[4]
    }
`

**Comment by joaoventura** [comment]
Fixed on #3c9b810. Thanks!

**Pull request closed without merging**
